server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security?serverTimezone=Asia/Shanghai
    username: ${DB_USERNAME:hgc}
    password: ${DB_PASSWORD:Hh209694}
    driver-class-name: com.mysql.cj.jdbc.Driver
security:
  jwt:
    secretKey: ${JWT_SECREKEY:world}